# Generated by Django 4.1.1 on 2022-09-19 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0003_itemsmens_itemswomens'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemsCategory',
            fields=[
                ('category', models.CharField(max_length=500, primary_key=True, serialize=False)),
            ],
        ),
    ]
